networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata_filestorage:
  minio_data_filestorage:
  minio_data_analytics:
  reports_data:

services:
  postgres-filestorage:
    image: postgres:16-alpine
    container_name: postgres-filestorage
    environment:
      POSTGRES_USER: filestorage
      POSTGRES_PASSWORD: filestorage
      POSTGRES_DB: filestorage
    ports:
      - "5432:5432"
    volumes:
      - pgdata_filestorage:/var/lib/postgresql/data
      - ../fileStoringService/migrations:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  minio-filestorage:
    image: minio/minio:latest
    container_name: minio-filestorage
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_filestorage:/data
    networks:
      - mynetwork

  file-storage-service:
    build:
      context: ../fileStoringService
      dockerfile: dockerfile
    container_name: file-storage-service
    depends_on:
      - postgres-filestorage
      - minio-filestorage
    environment:
      DATABASE_URL: postgres://filestorage:filestorage@postgres-filestorage:5432/filestorage?sslmode=disable
      S3_ENDPOINT: minio-filestorage:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: files
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    restart: always

  minio-analytics:
    image: minio/minio:latest
    container_name: minio-analytics
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9002:9000"
      - "9003:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_analytics:/data
    networks:
      - mynetwork

  file-analysis-service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: file-analysis-service
    depends_on:
      - file-storage-service
      - minio-analytics
    environment:
      FILE_STORAGE_URL: "http://file-storage-service:8080"
      S3_ENDPOINT: minio-analytics:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: reports
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    restart: always
